// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamDeckWindows;

#nullable disable

namespace SteamDeckWindows.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SteamDeckWindows.Models.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SteamDeckWindows.Models.Tool", b =>
                {
                    b.Property<int>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ToolId");

                    b.HasIndex("SettingId");

                    b.ToTable("Tool");
                });

            modelBuilder.Entity("SteamDeckWindows.Models.Tool", b =>
                {
                    b.HasOne("SteamDeckWindows.Models.Setting", null)
                        .WithMany("Tools")
                        .HasForeignKey("SettingId");
                });

            modelBuilder.Entity("SteamDeckWindows.Models.Setting", b =>
                {
                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
