theme: jekyll-theme-minimal
title: GitHub pages template
description: A simple template based on minimal jekyll theme
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Install Windows 11
    url: install-windows-11
  - title: Setup
    url: setup
