theme: jekyll-theme-minimal
title: Steam Deck Windows
description: This tool will help you setup and configure Windows 11 on your steam deck
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Install Windows 11
    url: install-windows-11
  - title: Drivers
    url: drivers
  - title: Emulators
    url: emulators
  - title: Hotkeys
    url: hotkeys
  - title: Tools
    url: tools
  - title: Developer Guide
    url: developer-guide
